[project]
name = "dsc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-generativeai>=0.8.4",
    "langchain>=0.3.23",
    "mesop>=1.0.1",
    "pinecone>=6.0.2",
]
